name: ""
verbose: ${verbose}
loss_function: "mse"   # loss function to use for training
num_conditional_channels: 0  # To be used for, e.g., diffusion models
#################################################################################################