# @package _global_
# to execute this module run:
# python run.py module=interpolation

defaults:
  - /module@_here_: _base_experiment_config.yaml   # base experiment config with defaults params
  - _self_

module:
  _target_: src.experiment_types.interpolation.InterpolationExperiment
  stack_window_to_channel_dim: True

datamodule:
  horizon: 6   # needs to be > 1

model:
  with_time_emb: True